-- +goose Up
CREATE TABLE content_sections (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, app_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(80) NOT NULL, description VARCHAR(500) NOT NULL DEFAULT '', status VARCHAR(20) NOT NULL DEFAULT 'active', sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY(id), KEY idx_sections_app(app_id,status,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE content_posts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, app_id BIGINT UNSIGNED NOT NULL, section_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(200) NOT NULL, content MEDIUMTEXT NOT NULL, media_json JSON NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', review_reason VARCHAR(500) NOT NULL DEFAULT '',
  price_cents BIGINT UNSIGNED NOT NULL DEFAULT 0, like_count INT UNSIGNED NOT NULL DEFAULT 0, comment_count INT UNSIGNED NOT NULL DEFAULT 0, view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL,
  PRIMARY KEY(id), KEY idx_posts_feed(app_id,status,id), KEY idx_posts_user(app_id,user_id,id),
  CONSTRAINT fk_post_section FOREIGN KEY(section_id) REFERENCES content_sections(id), CONSTRAINT fk_post_user FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE content_comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, app_id BIGINT UNSIGNED NOT NULL, post_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
  reply_to_user_id BIGINT UNSIGNED NULL, content VARCHAR(2000) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'published', pinned_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL, deleted_at DATETIME(6) NULL,
  PRIMARY KEY(id), KEY idx_comments_post(post_id,status,id), CONSTRAINT fk_comment_post FOREIGN KEY(post_id) REFERENCES content_posts(id), CONSTRAINT fk_comment_user FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE content_likes (app_id BIGINT UNSIGNED NOT NULL,post_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(post_id,user_id),KEY idx_likes_user(app_id,user_id,created_at),CONSTRAINT fk_like_post FOREIGN KEY(post_id) REFERENCES content_posts(id),CONSTRAINT fk_like_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE content_collections (app_id BIGINT UNSIGNED NOT NULL,post_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(post_id,user_id),KEY idx_collections_user(app_id,user_id,created_at),CONSTRAINT fk_collection_post FOREIGN KEY(post_id) REFERENCES content_posts(id),CONSTRAINT fk_collection_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE content_reports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,target_type VARCHAR(30) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,reason VARCHAR(500) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uniq_report(app_id,user_id,target_type,target_id),KEY idx_reports_review(app_id,status,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_notes (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(200) NOT NULL,content MEDIUMTEXT NOT NULL,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,deleted_at DATETIME(6) NULL,PRIMARY KEY(id),KEY idx_notes_user(app_id,user_id,updated_at),CONSTRAINT fk_note_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE products (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,name VARCHAR(200) NOT NULL,description TEXT NOT NULL,cover_asset_id BIGINT UNSIGNED NULL,price_cents BIGINT UNSIGNED NOT NULL,stock INT UNSIGNED NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(id),KEY idx_products_app(app_id,status,id),CONSTRAINT fk_product_cover FOREIGN KEY(cover_asset_id) REFERENCES media_assets(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE product_orders (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,order_no VARCHAR(64) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL,total_cents BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uniq_product_order(order_no),KEY idx_orders_user(app_id,user_id,id),CONSTRAINT fk_order_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_order_product FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sticker_packs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,cover_asset_id BIGINT UNSIGNED NULL,price_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(id),KEY idx_sticker_packs(app_id,status,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE stickers (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,pack_id BIGINT UNSIGNED NOT NULL,asset_id BIGINT UNSIGNED NOT NULL,sort_order INT NOT NULL DEFAULT 0,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),KEY idx_stickers_pack(pack_id,sort_order),CONSTRAINT fk_sticker_pack FOREIGN KEY(pack_id) REFERENCES sticker_packs(id),CONSTRAINT fk_sticker_asset FOREIGN KEY(asset_id) REFERENCES media_assets(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_sticker_packs (app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,pack_id BIGINT UNSIGNED NOT NULL,acquired_at DATETIME(6) NOT NULL,PRIMARY KEY(user_id,pack_id),CONSTRAINT fk_user_sticker_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_user_sticker_pack FOREIGN KEY(pack_id) REFERENCES sticker_packs(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE app_market_items (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,owner_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,description TEXT NOT NULL,icon_asset_id BIGINT UNSIGNED NULL,version VARCHAR(50) NOT NULL,package_url VARCHAR(1000) NOT NULL DEFAULT '',price_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'pending',download_count BIGINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,PRIMARY KEY(id),KEY idx_market(app_id,status,id),CONSTRAINT fk_market_owner FOREIGN KEY(owner_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO content_sections(app_id,name,description,status,sort_order,created_at,updated_at) VALUES(1,'综合','用户交流社区','active',0,NOW(6),NOW(6));

-- +goose Down
DROP TABLE app_market_items; DROP TABLE user_sticker_packs; DROP TABLE stickers; DROP TABLE sticker_packs; DROP TABLE product_orders; DROP TABLE products; DROP TABLE user_notes; DROP TABLE content_reports; DROP TABLE content_collections; DROP TABLE content_likes; DROP TABLE content_comments; DROP TABLE content_posts; DROP TABLE content_sections;
