-- +goose Up
ALTER TABLE users ADD COLUMN invitation_code VARCHAR(20) NULL AFTER username, ADD COLUMN invited_by BIGINT UNSIGNED NULL AFTER invitation_code, ADD UNIQUE KEY uniq_user_invitation_code (app_id,invitation_code), ADD CONSTRAINT fk_user_inviter FOREIGN KEY (invited_by) REFERENCES users(id);
UPDATE users SET invitation_code=UPPER(SUBSTRING(SHA2(CONCAT('BIM:',app_id,':',id),256),1,12)) WHERE invitation_code IS NULL;

CREATE TABLE user_follows (app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,follow_user_id BIGINT UNSIGNED NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(app_id,user_id,follow_user_id),KEY idx_user_fans(app_id,follow_user_id,user_id),CONSTRAINT fk_follow_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_follow_target FOREIGN KEY(follow_user_id) REFERENCES users(id),CONSTRAINT chk_follow_not_self CHECK(user_id<>follow_user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_signins (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,signin_date DATE NOT NULL,streak_days INT UNSIGNED NOT NULL DEFAULT 1,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uniq_user_signin(app_id,user_id,signin_date),KEY idx_signin_date(app_id,signin_date,user_id),CONSTRAINT fk_signin_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_badges (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,app_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,code VARCHAR(64) NOT NULL,name VARCHAR(100) NOT NULL,icon_asset_id BIGINT UNSIGNED NULL,awarded_at DATETIME(6) NOT NULL,worn TINYINT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(id),UNIQUE KEY uniq_user_badge(app_id,user_id,code),CONSTRAINT fk_badge_user FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT fk_badge_asset FOREIGN KEY(icon_asset_id) REFERENCES media_assets(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- +goose Down
DROP TABLE user_badges;DROP TABLE user_signins;DROP TABLE user_follows;ALTER TABLE users DROP FOREIGN KEY fk_user_inviter,DROP KEY uniq_user_invitation_code,DROP COLUMN invited_by,DROP COLUMN invitation_code;
