<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ApiError, request } from '../api/client'
type Row=Record<string,unknown>
const tabs=[['content/posts','帖子审核'],['content/reports','举报处理'],['products','商品'],['sticker-packs','表情商店'],['market','应用审核'],['merchants','商户'],['withdrawals','提现审核']] as const
const active=ref<string>(tabs[0][0]);const rows=ref<Row[]>([]);const error=ref('');const loading=ref(false)
async function load(){loading.value=true;error.value='';try{rows.value=await request<Row[]>(`/v1/portal/${active.value}`)}catch(e){error.value=e instanceof ApiError?e.message:'加载失败'}finally{loading.value=false}}
async function review(row:Row,status:string){const id=row.id??row.user_id;const suffix=active.value==='content/posts'||active.value==='market'||active.value==='merchants'||active.value==='withdrawals'?'/review':'';const path=active.value==='content/reports'?`/v1/portal/content/reports/${id}`:`/v1/portal/${active.value}/${id}${suffix}`;try{await request(path,{method:'PUT',body:JSON.stringify({status,reason:status==='rejected'?'未通过运营审核':'审核通过'})});await load()}catch(e){error.value=e instanceof ApiError?e.message:'操作失败'}}
function select(value:string){active.value=value;load()}
function actions(){if(active.value==='content/posts'||active.value==='market')return [['published','通过'],['rejected','拒绝']];if(active.value==='content/reports')return [['resolved','已处理'],['rejected','驳回']];if(active.value==='merchants')return [['approved','开通'],['rejected','拒绝'],['disabled','停用']];if(active.value==='withdrawals')return [['completed','完成'],['rejected','拒绝']];return []}
onMounted(load)
</script>
<template><div class="page"><div class="heading"><div><h1>内容与交易运营</h1><p>统一管理社区、商品、表情、应用、商户和提现审核</p></div><button @click="load">刷新</button></div><div class="tabs"><button v-for="tab in tabs" :key="tab[0]" :class="{active:active===tab[0]}" @click="select(tab[0])">{{tab[1]}}</button></div><p v-if="error" class="error">{{error}}</p><div class="table"><table><thead><tr><th>编号</th><th>主要信息</th><th>状态</th><th>详情</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="String(row.id??row.user_id)"><td>{{row.id??row.user_id}}</td><td><strong>{{row.title??row.name??row.nickname??row.order_no??row.target_type}}</strong><small>{{row.author??row.username??row.user??row.reporter??row.version??''}}</small></td><td>{{row.status??'-'}}</td><td>{{row.reason??row.review_reason??row.description??row.account_masked??'-'}}</td><td><button v-for="item in actions()" :key="item[0]" class="link" @click="review(row,item[0])">{{item[1]}}</button></td></tr><tr v-if="!loading&&!rows.length"><td colspan="5" class="empty">暂无数据</td></tr></tbody></table></div></div></template>
<style scoped src="../design/admin-page.css"></style><style scoped>.tabs{display:flex;gap:0;overflow:auto;margin-bottom:16px;border-bottom:1px solid var(--bim-border)}.tabs button{border:0;border-bottom:2px solid transparent;white-space:nowrap}.tabs button.active{color:var(--bim-primary);border-bottom-color:var(--bim-primary)}td .link+.link{margin-left:10px}.empty{text-align:center;color:var(--bim-muted);padding:48px}</style>
