<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ApiError, request } from '../api/client'

interface Account { user_id:number;username:string;nickname:string;available:string;frozen:string;currency:string;status:string;lock_reason:string;updated_at:string }
const accounts=ref<Account[]>([]);const loading=ref(false);const error=ref('');const selected=ref<Account|null>(null);const action=ref('lock');const amount=ref('');const reason=ref('');const saving=ref(false)
async function load(){loading.value=true;error.value='';try{accounts.value=await request<Account[]>('/v1/wallet/accounts?app_id=1&limit=100')}catch(e){error.value=e instanceof ApiError?e.message:'加载失败'}finally{loading.value=false}}
function open(item:Account){selected.value=item;action.value=item.status==='locked'?'unlock':'lock';amount.value='';reason.value=''}
async function submit(){if(!selected.value)return;saving.value=true;error.value='';try{await request(`/v1/wallet/accounts/${selected.value.user_id}/control`,{method:'POST',body:JSON.stringify({app_id:1,action:action.value,amount:amount.value,reason:reason.value})});selected.value=null;await load()}catch(e){error.value=e instanceof ApiError?e.message:'操作失败'}finally{saving.value=false}}
onMounted(load)
</script>

<template>
  <div class="page"><div class="title"><div><h1>平台钱包</h1><p>人民币余额、冻结金额和钱包状态</p></div><button @click="load">刷新</button></div><p v-if="error" class="error">{{ error }}</p><div class="table-wrap"><table><thead><tr><th>用户</th><th>可用余额</th><th>冻结余额</th><th>状态</th><th>原因</th><th></th></tr></thead><tbody><tr v-for="item in accounts" :key="item.user_id"><td><strong>{{ item.nickname }}</strong><small>@{{ item.username }}</small></td><td>¥ {{ item.available }}</td><td>¥ {{ item.frozen }}</td><td>{{ item.status==='active'?'正常':'已锁定' }}</td><td>{{ item.lock_reason || '-' }}</td><td><button class="link" @click="open(item)">管控</button></td></tr><tr v-if="!loading&&!accounts.length"><td colspan="6" class="empty">暂无钱包数据</td></tr></tbody></table></div><div v-if="selected" class="dialog-backdrop" @click.self="selected=null"><form class="dialog" @submit.prevent="submit"><h2>钱包管控</h2><p>{{ selected.nickname }} · @{{ selected.username }}</p><label>操作<select v-model="action"><option value="lock">锁定钱包</option><option value="unlock">解除锁定</option><option value="freeze">冻结余额</option><option value="unfreeze">解冻余额</option><option value="unlock_payment_password">解锁支付密码</option></select></label><label v-if="action==='freeze'||action==='unfreeze'">金额<input v-model="amount" inputmode="decimal" placeholder="0.00" required /></label><label>操作原因<textarea v-model.trim="reason" maxlength="500" required /></label><div class="actions"><button type="button" @click="selected=null">取消</button><button class="primary" :disabled="saving">确认</button></div></form></div></div>
</template>

<style scoped>
.page{max-width:1280px}.title{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}h1{margin:0;font-size:24px}p{margin:6px 0 0;color:var(--bim-muted)}button{height:34px;padding:0 14px;border:1px solid var(--bim-border);background:#fff}.table-wrap{overflow:auto;background:#fff;border:1px solid var(--bim-border)}table{width:100%;border-collapse:collapse;min-width:800px}th,td{padding:14px 16px;text-align:left;border-bottom:1px solid var(--bim-border);font-size:14px}th{background:var(--bim-fill);color:var(--bim-muted);font-weight:600}td small{display:block;color:var(--bim-muted);margin-top:3px}.link{border:0;color:var(--bim-primary)}.empty{text-align:center;color:var(--bim-muted);padding:48px}.error{color:var(--bim-danger);margin-bottom:12px}.dialog-backdrop{position:fixed;inset:0;background:rgba(20,24,31,.42);display:grid;place-items:center;padding:20px}.dialog{width:min(440px,100%);background:#fff;padding:24px}.dialog h2{margin:0}.dialog label{display:grid;gap:7px;margin-top:18px;font-size:14px;color:var(--bim-muted)}select,input,textarea{border:1px solid var(--bim-border);padding:10px;background:#fff}textarea{min-height:90px;resize:vertical}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.primary{background:var(--bim-primary);color:#fff;border-color:var(--bim-primary)}
</style>
